### ISSUE TITLE
URLごとにも平均時間が出せると嬉しい

### ISSUE THREAD

**Issue by akkinoc** [waniji/benchmark-tool#1]
URLごとの平均も出して、どのポイントが遅いとかも分かると嬉しいな～！

最後に出るレポートもJSON化されてると、
ソートしたり色々使い勝手良さそう :smile_cat:

**Comment by waniji** [comment]
318a85d510afdb09b4fe25be216bb15e6a625f52 でURL別に結果を表示するようにしました :smiley: 
JSON形式にしたりソート機能をつけたりは、今後の改修に期待してください :full_moon_with_face:

**Comment by akkinoc** [comment]
(☆｀・ω・´)ｂｸﾞｯ

**Comment by waniji** [comment]
別Issueに切り出しました :beer: 

#4 ソート機能
#5 結果のフォーマット変更(Table/JSON)
